// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNIZ9Ai-GKEAIUeTXcmO38zx4AYmONw64',
    appId: '1:558848817521:web:867fcc4a53acc97dd21ed0',
    messagingSenderId: '558848817521',
    projectId: 'geo-base-1a00b',
    authDomain: 'geo-base-1a00b.firebaseapp.com',
    storageBucket: 'geo-base-1a00b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_c-BuJMy8MGHfhG-2Yv9RLk0POmudDyg',
    appId: '1:558848817521:android:1d858594a37676ded21ed0',
    messagingSenderId: '558848817521',
    projectId: 'geo-base-1a00b',
    storageBucket: 'geo-base-1a00b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIMTZEQYaZoYlyeKT3fY_ZDl9akqSI8Og',
    appId: '1:558848817521:ios:5a9a1460b91dd676d21ed0',
    messagingSenderId: '558848817521',
    projectId: 'geo-base-1a00b',
    storageBucket: 'geo-base-1a00b.appspot.com',
    iosClientId: '558848817521-2hcdstko5mv5ce9ut8v8ac1ahft2r32o.apps.googleusercontent.com',
    iosBundleId: 'com.example.geoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIMTZEQYaZoYlyeKT3fY_ZDl9akqSI8Og',
    appId: '1:558848817521:ios:b2d79048451140c4d21ed0',
    messagingSenderId: '558848817521',
    projectId: 'geo-base-1a00b',
    storageBucket: 'geo-base-1a00b.appspot.com',
    iosClientId: '558848817521-malvht2e2orv5kpk0bgudvjvpu1t9590.apps.googleusercontent.com',
    iosBundleId: 'com.example.geoChat.RunnerTests',
  );
}
